### ISSUE TITLE
Strange bug with animation

### ISSUE THREAD

**Issue by Ducasse** [pharo-graphics/Bloc#532] opened 2024-06-12 13:50 UTC
We have an animation that decrease a number and we have no idea why it stops before the end on my machine but not the one of alexis. 

To reproduce

```
Metacello new
	baseline: 'CoypuIDE';
	repository: 'github://pharo-graphics/CoypuIDE/';
	onConflict: [ :ex | ex useIncoming ];
	onUpgrade: [ :ex | ex useIncoming ];
	load.
```

```
MfTimerElement exampleSimpleTimer
```

On my machine it produces 

![Capture 2024-06-12 at 15 49 09](https://github.com/pharo-graphics/Bloc/assets/432549/ca126677-dd20-497c-8e22-074cc5292ef0)

when I click a lot (6 times fast instead of one) I get 

![Capture 2024-06-12 at 15 49 50](https://github.com/pharo-graphics/Bloc/assets/432549/413d17fa-615f-48c2-b4d3-86b77f649ff0)

**Comment by rvillemeur** [comment] 2024-07-02 21:10
I have randomly similar behavior; With current code, the counter rarely goes down to 0.

I would suggest this code, which is really done for number transition:

```smalltalk
initializeAnimation

	| started |
	anim := BlNumberTransition new
		        from: 0;
		        to: value;
		        by: 1;
		        duration: value seconds;
		        "onStepDo: is called on every space pulse. Color are updated at each pulse..."
		        onStepDo: [ :aValue :anElement |
			        | currentValue |
			        currentValue := value - aValue.
			        currentAngle := 360 - (decreasingAngleStep * aValue).
			        self updateAnnulusAngle: currentAngle.
			        self updateValue: currentValue.
			        "self background: Color random" ].


	started := false.

	self addEventHandlerOn: BlMouseDownEvent do: [ :a |
		started ifFalse: [
			started := true.
			self addAnimation: anim ] ]
```

**Comment by Ducasse** [comment] 2024-07-03 16:17
We got this too and it depends on the machine. I got this bug on my M2 but impossible to reproduce it on alexis' machine

**Comment by rvillemeur** [comment] 2024-07-03 16:20
The solution I suggest works (or at least, I cannot reproduce similar bug). Who else could try it as a workaround initial bug ?

**Comment by rvillemeur** [comment] 2024-07-03 16:44
I guess, on your M2 machine, the animation was even faster to start, which may explain the discrepancy

**Comment by tinchodias** [comment] 2024-07-03 17:31
@Ducasse I couldn't reproduce the bug on my Macbook Pro 2018 (intel)

**Comment by tinchodias** [comment] 2024-07-03 18:58
I think the solution of @rvillemeur is correct, it's the Bloc user in this case who must take care of now adding the animation if another is currently running. Right?

**Comment by rvillemeur** [comment] 2024-07-03 19:14
A last version, using BlAnimation API, removing the need for started variable:

```smalltalk
initializeAnimation

	anim := BlAnimation new
		        duration: 1 seconds;
		        loops: value;
		        addEventHandler: (BlEventHandler
				         on: BlAnimationLoopDoneEvent
				         do: [ :e |
					         currentAngle := currentAngle - decreasingAngleStep.
					         self updateAnnulusAngle: currentAngle.
					         self updateValue.
					         self background: Color random ]).

	self
		addEventHandlerOn: BlMouseDownEvent
		do: [ :a | anim isRunning ifFalse: [ self addAnimation: anim ] ]
```

**Comment by tinchodias** [comment] 2024-07-24 22:14
@Ducasse do you consider @rvillemeur's code snippet closes this issue?

**Comment by Ducasse** [comment] 2024-07-25 06:26
I do not know I should check on the timer code.

**Comment by Ducasse** [comment] 2024-07-25 06:28
But this is really important to document this behavior. 
It should be added to the chapter on animations.

**Comment by rvillemeur** [comment] 2024-07-25 15:57
I'll add it to graphic book  next week

Renaud

25 juil. 2024, 08:29 de ***@***.***:

**Comment by tinchodias** [comment] 2024-09-30 16:23
Were you able to add it to the book @rvillemeur ?

**Comment by rvillemeur** [comment] 2024-09-30 17:08
@tinchodias , updated information on animation were added. You can have a look here: https://github.com/SquareBracketAssociates/Booklet-Graphics/blob/main/Chapters/bloc/animation.md. Let me know if you have any comment.

**Comment by tinchodias** [comment] 2024-11-15 14:22
The documentation in general and about animation looks great. Thank you. So I close this issue.

**Closed by tinchodias** 2024-11-15 14:22 UTC
