### ISSUE TITLE
Effects

### ISSUE THREAD

**Issue by fool-in-the-rain** [pharo-graphics/Bloc#191] opened 2022-11-12 23:20 UTC
Hi, our work is already deeply indebted to the effects which made presentations so lively in Pharo 7 with Skia.   Could these **effects**, such as **BlGaussianShadowEffect**, and **drop shadow**, be revived for the current implementation of **Cairo Alexandrie**?   The gaussian effect is huge.

 If you could also consider some creative opportunities for the **mesh gradient**, that is another effect which would help rivet peoples' attention.  Anything to help shine a light on the underlying technology is a big plus for us.

**Comment by tinchodias** [comment] 2022-12-20 23:21
Hi, we now have shadows. Since [this commit](https://github.com/pharo-graphics/Bloc/commit/8cd06cbe6ff91c447663931607006c27d320b644). Feedback welcome!

Warning: it's slow. I have to improve this with:
- caching
- taking advantage of each particular geometry


There is the Gaussian shadow:

```
		aBlElement effect:
			(BlGaussianShadowEffect
				color: Color orange
				width: 5
				offset: 0@0 )
```

From our regression tests:

![](https://raw.githubusercontent.com/pharo-graphics/Bloc/577d5a6fa57abd7fe627553b0fd139d7f46ec837/tests/render/buildGaussianShadowsByGeometry.png)

![](https://raw.githubusercontent.com/pharo-graphics/Bloc/577d5a6fa57abd7fe627553b0fd139d7f46ec837/tests/render/buildGaussianShadowsByCircleSector.png)


![](https://raw.githubusercontent.com/pharo-graphics/Bloc/577d5a6fa57abd7fe627553b0fd139d7f46ec837/tests/render/buildGaussianShadowsByOutskirt.png)


![](https://raw.githubusercontent.com/pharo-graphics/Bloc/577d5a6fa57abd7fe627553b0fd139d7f46ec837/tests/render/buildGaussianShadowsByTextTransformations.png)

---

And also the "simple" shadow, that is like the Gaussian with width=0, i.e. sharp edges. Example:

```
		aBlElement effect:
			(BlSimpleShadowEffect
				color: Color orange
				offset: 1 @ 1 ) 
```

**Comment by tinchodias** [comment] 2022-12-20 23:36
![imagen](https://user-images.githubusercontent.com/3044265/208786396-d449d652-aa43-4b5a-b50e-26dba93ed7cc.png)

**Comment by astares** [comment] 2022-12-21 01:14
Cool!

**Comment by tinchodias** [comment] 2022-12-22 16:16
There was a visual bug in some cases, that is fixed with my latest commit on Alexandrie. 

(For the record: it took me some debug time to detect the bug happened when the pixel width of the Cairo surface was different than it's stride)

**Comment by tinchodias** [comment] 2023-01-03 23:37
The mesh gradient is already implement in Athens-Cairo, so shouldn't be hard to port it to Alexandrie, and add a new Bloc paint.

I am taking a glance at [COLR spec](https://learn.microsoft.com/en-us/typography/opentype/spec/colr#sweep-gradients) and they call it sweep gradient.

**Comment by tinchodias** [comment] 2023-01-03 23:39
Correction: the sweep gradient is an application of the mesh gradient. Here is a cairo test that shows how to do it: https://gitlab.freedesktop.org/cairo/cairo/-/blob/master/test/mesh-pattern-conical.c

**Comment by tinchodias** [comment] 2024-12-06 19:24
We keep open issue 333 for conical gradient and close this, which is too wide

**Closed by tinchodias** 2024-12-06 19:24 UTC
