### ISSUE TITLE
OSWindow - SDL2 does not close

### ISSUE THREAD

**Issue by Ducasse** [pharo-graphics/Bloc#70] opened 2020-10-14 06:56 UTC
In Pharo 80 using SDL 20 (see setting)
a window opens but cannot get closed.
![Screenshot 2020-10-14 at 08 56 04](https://user-images.githubusercontent.com/432549/95954124-1ed28e80-0dfb-11eb-8ed8-eb5507d35702.png)

**Comment by tinchodias** [comment] 2021-03-05 21:28
Right now (loading NewBloc), I don't see that option.

<img width="422" alt="Screen Shot 2021-03-05 at 18 28 14" src="https://user-images.githubusercontent.com/3044265/110175456-8efca380-7de0-11eb-8823-72923dd8bc23.png">

**Comment by tinchodias** [comment] 2021-03-12 20:41
The required packages for OSWindow are now included in NewBloc, so my previous comment is invalid. 
Now... how to reproduce it? I think this happened to me in linux, I will try again.

**Comment by tinchodias** [comment] 2021-03-12 20:45
The following code reproduces the error on linux, but there is an error that may be the reason:

~~~
space := BlSpace new.
space host: BlOSWindowSDL2Host new.
space show. 
~~~

Steps:
1. In Debian 10, load 90+vmHeadlessLatest
2. Load NewBloc
3. Execute the code (above)
4. The window doesn't respond to the close button on the title bar. But you have this error on the image: https://github.com/pharo-graphics/Bloc/issues/123

**Comment by tinchodias** [comment] 2023-03-15 19:54
Can't reproduce now. Let's close it.

**Closed by tinchodias** 2023-03-15 19:54 UTC
