### ISSUE TITLE
Bug in BlLayout: [Post-mortem] #insets was sent to nil

### ISSUE THREAD

**Issue by LANDAISB** [pharo-graphics/Bloc#457] opened 2024-03-04 13:21 UTC
I have an exception in class BlLayout and method measureChildWithMargins.

```
measureChildWithMargins: anElement parentSpec: parentSpec widthUsed: widthUsed heightUsed: heightUsed
"Measure anElement based on provided parent's extent measurement specification and used width and height
	taking element's margin and parent's padding into account"
	
self measureChild: anElement
		parentSpec: parentSpec
		widthUsed: anElement parent insets width + anElement outsets width + widthUsed
		heightUsed: anElement parent insets height + anElement outsets height + heightUsed
```

"Sometimes" anElement is not nil but anElement parent is nil, so I have an exception "[Post-mortem] #insets was sent to nil".

The use case is to add and remove some BlTextElement to a parent BlElement.

**Comment by labordep** [comment] 2024-03-05 16:04
@LANDAISB wrote an unit test example to illustrate the problem.
Copy the method below and add it in a `TestCase` class. 
Execute the test.

```smalltalk
testAddAndRemoveInBlElementWithConcurrent

                | workerAdd workerRemove parent isTask1Finished isTask2Finished isException isExceptionClose blSpace |

                isException := false.
                isExceptionClose := false.
                isTask1Finished := false.
                isTask2Finished := false.
                
                parent := BlElement new.
                parent layout: BlLinearLayout vertical.
                parent layout horizontalAlignment: BlElementAlignment left.
                parent layout cellSpacing: 10.
                parent layout interspace: 10.
                parent size: 300@500.
                parent constraintsDo: [ :c |
                               c frame vertical alignTop.
                               c frame horizontal alignLeft ].
                
                blSpace := parent openInSpace.
                
                workerAdd := TKTWorker new.
                workerAdd priority: Processor userSchedulingPriority.
                workerAdd start.
                workerAdd schedule:[
                               [ 1 to:200 do:[:i | | text |
                                               text := String streamContents: [:s | s nextPutAll: 'Label'. s nextPutAll: i asString].
                                               
                                               parent addChild: (BlTextElement new text: text asRopedText; id: i asString asSymbol).
                                               2 milliSeconds wait.
                               ] ] on: Exception do:[:ex | isException := true. isTask1Finished := true. ex defaultAction].
                               isTask1Finished := true.
                ].

                10 milliSeconds wait.

                workerRemove := TKTWorker new.
                workerRemove priority: Processor userSchedulingPriority.
                workerRemove start.
                workerRemove schedule:[[
                               [parent children isNotEmpty] whileTrue:[ | childEl |
                                               childEl := parent children asSet asOrderedCollection shuffled first. 
                                               childEl ifNotNil:[ parent removeChild: childEl].
                                               3 milliSeconds wait.
                               ]
                ] on: Exception do:[:ex | isException := true. isTask2Finished := true. ex defaultAction].
                               isTask2Finished := true.
                ].

                [[ isTask1Finished and:[ isTask2Finished  ]] whileFalse:[
                               5 milliSeconds wait.
                ]] on: Exception do:[:ex | isException := true. ex defaultAction].

                [blSpace close ] on: Exception do:[:ex | isExceptionClose := true. ex defaultAction].

                self assert: isException equals: false.
                self assert: parent children size equals: 0.
                self assert: isExceptionClose equals: false.

```

Sometimes there is this Exception: `[Post-mortem] #insets was sent to nil`
![image](https://github.com/pharo-graphics/Bloc/assets/49183340/f7a0def3-95ac-45bb-a1f2-881f38ae5848)

And the window cannot be closed with the "X" buttton:
![image](https://github.com/pharo-graphics/Bloc/assets/49183340/a7ba536e-5937-4383-94c1-4b1fb6b1fada)

Config:
- Bloc 59a4a10f42909a2fa3b4f00dd82432f5336409dd (today)
- Windows 10 Pro
- Pharo-11.0.0+build.725
- VM - 10.1.0.0

**Comment by plantec** [comment] 2024-03-05 16:13
maybe there is a need for a BlTask somewhere to avoid layouting phase processing conflict

**Comment by tinchodias** [comment] 2024-03-06 01:59
Is it a possibility for you to enqueue Space tasks to perform the addition and removal of elements? I'm rewriting the example to show you in code what I mean.

I would be something like:
```
1 to: 200 do: [ :i |
	blSpace enqueueTask:
		(BlTaskAction new
			 action: [  " add text element here " ];
			 yourself).
    2 milliSeconds wait ]
```

and similar for removing them...
This way, the change in the element's tree (add/remove) should be done in moment when it's fine for the space's main loop.

I think the problem in your example is that the Taskit task (at lower level this is another Process) changes the element's tree when it's not expected to be changed (while doing the layout phase of the space loop).

**Comment by labordep** [comment] 2024-03-06 10:36
Thanks @tinchodias. 
We are currently testing your suggestion in our application. We stayed up all night to confirm whether this issue has been fixed.

I have a related question: Is this concurrent access problem only associated with the addition or removal of children, or could we also encounter this problem when editing the BlElement property?

**Comment by tinchodias** [comment] 2024-03-07 14:14
Did it work with `BlTask`s? should we close this issue?

**Comment by tinchodias** [comment] 2024-03-08 02:33
I think using inUIProcessDo: is a possibility you can choose. Not sure what to recommend. Now that I analyzed the implementation, I think:
- it could be faster but also 
- may produce some unexpected behavior
because the implementation has an "if" that, in the case of being executed already in the "host loop" Process then it just executes the block immediately, but if it's another Process, then it enqueues a new BlTaskAction with the block, so it's postponed to be executed in the next host loop.

**Comment by tinchodias** [comment] 2024-03-08 02:35
BTW con convenience we may add to API a enqueueBlock: or enqueueAction: that receives aBlock and enqueues a `BlTaskAction` with it.

**Comment by tinchodias** [comment] 2024-03-11 12:26
Please reopen if needed

**Closed by tinchodias** 2024-03-11 12:26 UTC
Labels: bug, Thales
