### ISSUE TITLE
BlProportionalLayout strange behaviour when exported as Form while opened in space

### ISSUE THREAD

**Issue by Nyan11** [pharo-graphics/Bloc#561] opened 2024-07-24 08:50 UTC
Hello,

I was working with BlProportionalLayout with Pyramid and found strange behaviour with the exportAsForm method.

# Bug reproduction

## No bug

In this example i create an element A (who has a proportional layout).
A has a child B (who has a proportional layout).
B has child C.

```st
application := (BlElement new
   constraintsDo: [:constraints |  constraints horizontal matchParent.
      constraints vertical matchParent.
      constraints padding: (BlInsets all: 10.0) ];
   id: #A;
   layout: BlProportionalLayout new;
   addChildren: {(BlElement new
         constraintsDo: [:constraints |  constraints proportional horizontal right: 0.5.
            constraints padding: (BlInsets all: 10.0) ];
         id: #B;
         layout: BlProportionalLayout new;
         addChildren: {(BlElement new
               constraintsDo: [:constraints |  constraints proportional vertical bottom: 0.3 ];
               id: #C;
               background: (BlPaintBackground new
                     paint: (BlColorPaint new
                           color: (Color r: 1.0 g: 0.0 b: 0.0 alpha: 1.0);
                           yourself);
                     opacity: 1.0;
                     yourself);
               yourself)};
         background: (BlPaintBackground new
               paint: (BlColorPaint new
                     color: (Color r: 1.0 g: 1.0 b: 1.0 alpha: 1.0);
                     yourself);
               opacity: 1.0;
               yourself);
         yourself)};
   background: (BlPaintBackground new
         paint: (BlColorPaint new
               color: (Color r: 0.0 g: 0.0 b: 1.0 alpha: 1.0);
               yourself);
         opacity: 1.0;
         yourself);
   yourself).

application openInSpace.

"Wait until the space is shown before executing the next line"
formB := (application childNamed: #B) exportAsForm.
```

If i inspect the formB (the form of the element B) i obtain the correct image.
![image](https://github.com/user-attachments/assets/cd349295-b29f-409e-99a5-427455622e61)

## With the bug

I do the same but this time i create a form from the element C.

```st
application := (BlElement new
   constraintsDo: [:constraints |  constraints horizontal matchParent.
      constraints vertical matchParent.
      constraints padding: (BlInsets all: 10.0) ];
   id: #A;
   layout: BlProportionalLayout new;
   addChildren: {(BlElement new
         constraintsDo: [:constraints |  constraints proportional horizontal right: 0.5.
            constraints padding: (BlInsets all: 10.0) ];
         id: #B;
         layout: BlProportionalLayout new;
         addChildren: {(BlElement new
               constraintsDo: [:constraints |  constraints proportional vertical bottom: 0.3 ];
               id: #C;
               background: (BlPaintBackground new
                     paint: (BlColorPaint new
                           color: (Color r: 1.0 g: 0.0 b: 0.0 alpha: 1.0);
                           yourself);
                     opacity: 1.0;
                     yourself);
               yourself)};
         background: (BlPaintBackground new
               paint: (BlColorPaint new
                     color: (Color r: 1.0 g: 1.0 b: 1.0 alpha: 1.0);
                     yourself);
               opacity: 1.0;
               yourself);
         yourself)};
   background: (BlPaintBackground new
         paint: (BlColorPaint new
               color: (Color r: 0.0 g: 0.0 b: 1.0 alpha: 1.0);
               yourself);
         opacity: 1.0;
         yourself);
   yourself).

application openInSpace.

"Wait until the space is shown before executing the next line"
formB := ((application childNamed: #B) childNamed: #C) exportAsForm.
```

![image](https://github.com/user-attachments/assets/0253d390-46e6-4e23-aea7-1222513c5acd)

# Explication

In the second example the B element (in white) has changed its size to 50px by 50px when we exported it as a Form.

# Others

Bloc version : fa019a70153cdd329de2e0f88a29d1a63c46661a 2024-07-18 18:55 (master)
Pharo 12.0.0
Build information: Pharo-12.0.0+SNAPSHOT.build.1523.sha.3fd20c14be4ec63710f40bb8eb486e1eaf262af2 (64 Bit)

**Comment by Nyan11** [comment] 2024-07-24 08:52
https://github.com/pharo-graphics/Bloc/issues/560 could be linked ?

**Comment by tinchodias** [comment] 2024-07-24 17:07
@Nyan11 yes I think this is a consequence of #560. How is this `exportAsForm` sent in your context? is this debugging from Workspace, or is the tool doing it normally?

**Comment by Nyan11** [comment] 2024-07-24 18:29
Hello,

I use it to create a ghost effect for the drag and drop of an application.

I did not find the bug using the debugger or the inspector but by playing with my drag and drop.

**Comment by tinchodias** [comment] 2024-07-24 20:32
Okay. We have to find a solution.

About the reproduce instructions... is this right?
I select the "With the bug" script up to sending "openInSpace", and "do it". The SDL2 window is opened, then I sitch back to the Pharo IDE, I select the last line and "inspect it", and I get this:

<img width="455" alt="Screenshot 2024-07-24 at 16 17 40" src="https://github.com/user-attachments/assets/ac666b13-d75a-4905-96ea-8ef4b684da79">

Which is not exactly what you report, but the second time a "inspect it", I get:

<img width="367" alt="Screenshot 2024-07-24 at 16 17 46" src="https://github.com/user-attachments/assets/ad29207a-f334-43e1-8bc6-d0e7c94b154c">

**Comment by tinchodias** [comment] 2024-07-24 20:34
As a workaround to #560, I'd try to export to form when layout is not requested, or wait if it is requested. I wrote the following modification to your bug script, but I see the same results as in my previous comment (first + second time inspect):

```smalltalk
"Wait until the space is shown before executing the next line"

c := (application childWithId: #B) childWithId: #C.
c isLayoutRequested
	ifTrue: [
		{Time now. 'postpone export'} traceCr.
		form := c whenLayoutedDoOnce: [
			{Time now. '--> export done'} traceCr.
			c exportAsForm inspect ] ]
	ifFalse: [
		{Time now. 'ready to export'} traceCr.
		form := c exportAsForm inspect.
		{Time now. '--> export done'} traceCr ]
```

**Comment by Nyan11** [comment] 2024-07-24 20:36
Do you see any change on the opened BlSpace ?

On my example (with the bug) the white element changes its size (inside the space) when i generate the form.

**Comment by tinchodias** [comment] 2024-07-24 20:42
Yes, it changes size like this, when I select all and do it (http://ws.stfx.eu/AEWFNKGGOS93):

<img width="505" alt="Screenshot 2024-07-24 at 16 41 26" src="https://github.com/user-attachments/assets/5e082bfc-ace7-417d-8545-5556e80a574a">

**Comment by Nyan11** [comment] 2024-07-24 20:57
OK, this is the bug i wanted to report. You are doing the reproduction correctly

**Comment by tinchodias** [comment] 2024-07-24 21:00
Thanks, I'm debugging it. For now I'd say it's not #560, because export is done when isLayoutRequested is false, and this happens anyway.

Also I noticed that when I resize the window, the elements come back to the expected size (with match parent).

**Comment by tinchodias** [comment] 2024-07-24 21:28
I was wrong in my previous comment, it IS #560. The script sends `exportAsForm`, which uses `BAFormExporter` and not `BlElement>>aeAsForm` as I thought... it's a separated implementation that always sends `forceLayout` to the exlement being exported. The exporter should only send forceLayout if it's requested...

**Comment by tinchodias** [comment] 2024-07-24 22:00
This was not specific to the proportional layout. Please review #564, which doesn't fix the race condition but fixes some errors I've found with your script (I have to add tests for the exporters in other PR!)

**Comment by Nyan11** [comment] 2024-07-25 07:41
i check #564, and it works well with my application but i found another bug.
I you modify the constraints value of the "C" element, the size is again reduce.


See:
```st
a := (BlElement new
   id: #A;
   background: Color red;
   constraintsDo: [:constraints |
      constraints horizontal matchParent.
      constraints vertical matchParent.
      constraints padding: (BlInsets all: 20.0) ];
   layout: BlProportionalLayout new;
   addChild: (BlElement new
         id: #B;
         background: Color green;
           effect: (BlSimpleShadowEffect
              color: Color white
              offset: 5 @ 15);
         constraintsDo: [:constraints |
            constraints proportional horizontal right: 0.7.
            constraints padding: (BlInsets all: 20.0) ];
         layout: BlProportionalLayout new;
         addChild: (BlElement new
               id: #C;
               background: Color blue;
               effect: (BlSimpleShadowEffect
                  color: Color white
                  offset: 5 @ 15);
               constraintsDo: [:constraints |
                 constraints proportional horizontal right: 0.7.
	              constraints frame vertical alignCenter ];
               yourself);
         yourself);
   yourself).

s := a openInSpace.
s extent: 400 asPoint.


"I reduce the proportion of the C element from 0.7 to 0.6"
constraintsMaybePostponedBlock := [ :e |
	e isLayoutRequested
		ifTrue: [
			{Time now. 'postpone export'} traceCr.
			form := e whenLayoutedDoOnce: [
				{Time now. 'ready to export'} traceCr.
				e constraintsDo: [:constraints |
                 constraints proportional horizontal right: 0.6 ] ]
			]
		ifFalse: [
			{Time now. 'ready to export'} traceCr.
				e constraintsDo: [:constraints |
                 constraints proportional horizontal right: 0.6 ]
			] ].

b := a childWithId: #B.
c := b childWithId: #C.

constraintsMaybePostponedBlock value: c.
```

Without the postpone block:
![image](https://github.com/user-attachments/assets/3f526290-f334-4fc1-a8ae-cb66f275a6f3)

With the postpone block:
![image](https://github.com/user-attachments/assets/33bbdcb5-0a56-47db-a563-30c15f667167)

**Comment by tinchodias** [comment] 2024-07-26 15:56
Does this happen with other layouts? there is a bug I reported time ago still not fixed, on nested elements with proportional layout: https://github.com/pharo-graphics/Bloc/issues/318

**Comment by Nyan11** [comment] 2024-07-29 08:08
I think it does not. I tested with the flow, linear and frame layout.

**Comment by Nyan11** [comment] 2024-07-29 08:13
You have different behaviour when you have nested BlProportionalLayout.
I commented on https://github.com/pharo-graphics/Bloc/issues/318 for an example

**Comment by tinchodias** [comment] 2024-07-29 16:17
Thanks!! more examples help to debug it! Now that #564 is merged, do we close this issue?

**Comment by Nyan11** [comment] 2024-07-30 07:23
> I check #564, and the drag and drop effect works well with my application. But i found another bug if you modify the constraints value of the "C" element. The size is reduce.
> 
> See:
> 
> ```smalltalk
> a := (BlElement new
>    id: #A;
>    background: Color red;
>    constraintsDo: [:constraints |
>       constraints horizontal matchParent.
>       constraints vertical matchParent.
>       constraints padding: (BlInsets all: 20.0) ];
>    layout: BlProportionalLayout new;
>    addChild: (BlElement new
>          id: #B;
>          background: Color green;
>            effect: (BlSimpleShadowEffect
>               color: Color white
>               offset: 5 @ 15);
>          constraintsDo: [:constraints |
>             constraints proportional horizontal right: 0.7.
>             constraints padding: (BlInsets all: 20.0) ];
>          layout: BlProportionalLayout new;
>          addChild: (BlElement new
>                id: #C;
>                background: Color blue;
>                effect: (BlSimpleShadowEffect
>                   color: Color white
>                   offset: 5 @ 15);
>                constraintsDo: [:constraints |
>                  constraints proportional horizontal right: 0.7.
> 	              constraints frame vertical alignCenter ];
>                yourself);
>          yourself);
>    yourself).
> 
> s := a openInSpace.
> s extent: 400 asPoint.
> 
> 
> "I reduce the proportion of the C element from 0.7 to 0.6"
> constraintsMaybePostponedBlock := [ :e |
> 	e isLayoutRequested
> 		ifTrue: [
> 			{Time now. 'postpone export'} traceCr.
> 			form := e whenLayoutedDoOnce: [
> 				{Time now. 'ready to export'} traceCr.
> 				e constraintsDo: [:constraints |
>                  constraints proportional horizontal right: 0.6 ] ]
> 			]
> 		ifFalse: [
> 			{Time now. 'ready to export'} traceCr.
> 				e constraintsDo: [:constraints |
>                  constraints proportional horizontal right: 0.6 ]
> 			] ].
> 
> b := a childWithId: #B.
> c := b childWithId: #C.
> 
> constraintsMaybePostponedBlock value: c.
> ```
> 
> Without the postpone block: ![image](https://private-user-images.githubusercontent.com/34318678/352009109-3f526290-f334-4fc1-a8ae-cb66f275a6f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMjMxNjUsIm5iZiI6MTcyMjMyMjg2NSwicGF0aCI6Ii8zNDMxODY3OC8zNTIwMDkxMDktM2Y1MjYyOTAtZjMzNC00ZmMxLWE4YWUtY2I2NmYyNzVhNmYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDA3MDEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZmVlZmY3MjlhMGY1ZDgxMDljNzc0ZWU2ZjAyZWNhYTFjMDBlYmFhYTMyNmFkYjY0OGE1ZDkxOTRjNTMxNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yUDee_sOalxvR8KZeaKWaHckthSLvtsNFjhOEScZL9o)
> 
> With the postpone block: ![image](https://private-user-images.githubusercontent.com/34318678/352009732-33bbdcb5-0a56-47db-a563-30c15f667167.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMjMxNjUsIm5iZiI6MTcyMjMyMjg2NSwicGF0aCI6Ii8zNDMxODY3OC8zNTIwMDk3MzItMzNiYmRjYjUtMGE1Ni00N2RiLWE1NjMtMzBjMTVmNjY3MTY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDA3MDEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlZWQyMTI5NmI1YzJkYzFkYjg4YmIyY2FlN2ZmYzVmODYwMDY3M2E5MzI3NTU0OWI2YWU3NzkyMjU0MjcxNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oXlHxKHkDfu6Omn70l46HF31VlAHVdyeEpeRGD8wsTI)

There is this bug

**Comment by tinchodias** [comment] 2024-07-31 21:17
@Nyan11 I consider the bug you show in the script corresponds to #318 (there is no Form exported). So I close this, but don't hesitate to reopen if you consider it necessary.

**Closed by tinchodias** 2024-07-31 21:17 UTC
Labels: bug, Thales
